### ISSUE TITLE
Error exporting: Index is out of bounds of the array

### ISSUE THREAD

**Issue by remivamp** [Deinonychus71/Sm4shExplorer#1]
I keep getting this error when i try to export some stages like omega pacland and omega jungle hyjinks where it cant export any files from them.

**Comment by Deinonychus71** [comment]
It can happen for a lot of reasons, the most frequent being that you do not have dt00/dt01. Sm4shExplorer 0.04 is not meant to be used without a full dump + patch.
Also, if your dt00/dt01 doesnt match the version/region of your patch, it will also crash.

These are the two reasons. If it keeps crashing after fixing this, I would recommend waiting for the new version (SoonTM) and then send me the logs.
